[project]
name = "nb"
version = "0.1.0"
description = "my personal notebookes for a bunch of classes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.2",
    "numpy>=2.4.1",
]
